# Generated by Django 4.1.6 on 2023-06-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
